---
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Checkout roles
    command: ansible-galaxy install -r requirements.yml

  tasks:
  - name: Ensure the AWS config directory exists
    file:
      path: /root/.aws
      state: directory

  - name: Copy AWS CLI config
    template:
      src: templates/aws/config
      dest: /root/.aws/config
      mode: 0600

  - name: Copy AWS CLI credentials
    template:
      src: templates/aws/credentials
      dest: /root/.aws/credentials
      mode: 0600

  - name: Install AWS modules with PIP
    become: true
    pip:
      state: forcereinstall
      name:
      - awscli==1.16.193
      - boto3==1.9.183
      - boto==2.49.0
